version: '3'

services:
  foresight:
    build: .
    image: foresight
    container_name: foresight
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - DB_PORT=6379
    restart: always
  redis:
    image: "redis:6"

